### ISSUE TITLE
API check interval is too short

### ISSUE THREAD

**Issue by GRA0007** [BleckJeck/Yet_Another_Wanikani_Notifier#2]
As noted in pull request #1 the timeout to check the API is only 10 seconds, which makes sense to avoid reviews sticking around after completing them, but not necessary otherwise as new reviews on WK are only available every hour.

This issue is to track changing that timeout and getting the extension to watch when the user completes reviews to force-update the review count.

**Comment by BleckJeck** [comment]
To be fixed when updating the extension to comply with MV3 as the code will need rewriting to move from timers to alarms.
https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/#alarms

**Comment by BleckJeck** [comment]
By design chrome.alarms only allows for alarms to be set at maximum once very minute. Thus, converting the extension to MV3 also takes care of this issue. It does introduce a new UX problem, as while the users are doing their reviews, the badge can lag behind significantly (see also #4)
